version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TZ: Europe/Moscow
        USER_GROUP_ID: "${USER_GROUP_ID:-1000}"
        USER_ID: "${USER_ID:-1000}"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./system/php:/var/log/php
    depends_on:
      - pgsql
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    environment:
      FASTCGI_PASS: "${COMPOSE_PROJECT_NAME}-app-1:9000"
    volumes:
      - ./system/nginx:/var/log/nginx
      - ./:/var/www/bitrix
    env_file:
      - .env
    ports:
      - "${EXT_PORT}:80"
  pgsql:
    image: postgres
    restart: unless-stopped
    ports:
      - "${DB_PGSQL_EXT_PORT}:5432"
    environment:
      - TZ="Europe/Moscow"
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./system/postgresql:/var/log/postgresql
volumes:
  pgdata:
    driver: local
  php_logs:
    driver: local
  nginx_logs:
    driver: local
  postgresql_logs:
    driver: local