version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TZ: Europe/Moscow
        USER_GROUP_ID: "${USER_GROUP_ID:-1000}"
        USER_ID: "${USER_ID:-1000}"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./system/php:/var/log/php
    depends_on:
      - pgsql
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      FASTCGI_PASS: "tesk-app-1:9000"
    ports:
      - "${APP_EXT_PORT:-80}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
      - ./system/nginx:/var/log/nginx
    depends_on:
      - app
  pgsql:
    image: postgres
    restart: unless-stopped
    ports:
      - "${DB_PGSQL_EXT_PORT}:5432"
    environment:
      - TZ="Europe/Moscow"
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./system/postgresql:/var/log/postgresql
volumes:
  pgdata:
    driver: local
  php_logs:
    driver: local
  nginx_logs:
    driver: local
  postgresql_logs:
    driver: local